@startuml
node Node1 as n1
node &#34;Node 2&#34; as n2
file f1 as &#34;File 1&#34;
cloud c1 as &#34;this
is
a
cloud&#34;
cloud c2 [this
is
another
cloud]

n1 -&gt; n2
n1 --&gt; f1
f1 -&gt; c1
c1 -&gt; c2
@enduml