@startuml
node foo
foo --&gt; bar : normal
foo --&gt; bar1 #line:red;line.bold;text:red  : red bold
foo --&gt; bar2 #green;line.dashed;text:green : green dashed 
foo --&gt; bar3 #blue;line.dotted;text:blue   : blue dotted
@enduml