@startuml
title Bracketed line style mix
node foo
foo --&gt; bar                             : â
foo -[#red,thickness=1]-&gt; bar1          : [#red,1]
foo -[#red,dashed,thickness=2]-&gt; bar2   : [#red,dashed,2]
foo -[#green,dashed,thickness=4]-&gt; bar3 : [#green,dashed,4]
foo -[#blue,dotted,thickness=8]-&gt; bar4  : [blue,dotted,8]
foo -[#blue,plain,thickness=16]-&gt; bar5  : [blue,plain,16]
foo -[#blue;#green,dashed,thickness=4]-&gt; bar6  : [blue;green,dashed,4]
@enduml