const FONT_AWESOME_ICONS: Record<string, string> = {
    'fa-twitter': '\uf099',
    'fa-facebook': '\uf39e',
    'fa-github': '\uf09b',
    'fa-linkedin': '\uf08c',
    'fa-instagram': '\uf16d',
    'fa-youtube': '\uf167',
    'fa-google': '\uf1a0',
    'fa-microsoft': '\uf3ca',
    'fa-apple': '\uf179',
    'fa-amazon': '\uf270',
    'fa-docker': '\uf395',
    'fa-slack': '\uf198',
    'fa-figma': '\uf1c3',
    'fa-truck': '\uf0d1',
    'fa-truck-bold': '\uf0d1',
    'fa-user': '\uf007',
    'fa-users': '\uf0c0',
    'fa-home': '\uf015',
    'fa-cog': '\uf013',
    'fa-cogs': '\uf085',
    'fa-database': '\uf1c0',
    'fa-server': '\uf233',
    'fa-cloud': '\uf0c2',
    'fa-cloud-upload': '\uf0ee',
    'fa-cloud-download': '\uf0ed',
    'fa-envelope': '\uf0e0',
    'fa-phone': '\uf095',
    'fa-lock': '\uf023',
    'fa-unlock': '\uf09c',
    'fa-key': '\uf084',
    'fa-shield-alt': '\uf3ed',
    'fa-bell': '\uf0f3',
    'fa-star': '\uf005',
    'fa-heart': '\uf004',
    'fa-bookmark': '\uf02e',
    'fa-folder': '\uf07b',
    'fa-folder-open': '\uf07c',
    'fa-file': '\uf15b',
    'fa-file-alt': '\uf15c',
    'fa-file-code': '\uf1c9',
    'fa-image': '\uf03e',
    'fa-video': '\uf03d',
    'fa-search': '\uf002',
    'fa-filter': '\uf0b0',
    'fa-sync': '\uf021',
    'fa-check': '\uf00c',
    'fa-times': '\uf00d',
    'fa-plus': '\uf067',
    'fa-minus': '\uf068',
    'fa-exclamation-triangle': '\uf071',
    'fa-info-circle': '\uf05a',
    'fa-question-circle': '\uf059',
    'fa-ban': '\uf05e',
    'fa-bug': '\uf188',
    'fa-code': '\uf121',
    'fa-terminal': '\uf120',
    'fa-desktop': '\uf108',
    'fa-laptop': '\uf109',
    'fa-mobile': '\uf10b',
    'fa-tablet': '\uf10a',
    'fa-wifi': '\uf1eb',
    'fa-link': '\uf0c1',
    'fa-external-link-alt': '\uf35d',
    'fa-arrow-right': '\uf061',
    'fa-arrow-left': '\uf060',
    'fa-arrow-up': '\uf062',
    'fa-arrow-down': '\uf063',
    'fa-chevron-right': '\uf054',
    'fa-chevron-left': '\uf053',
    'fa-bars': '\uf0c9',
    'fa-list': '\uf03a',
    'fa-chart-bar': '\uf080',
    'fa-chart-line': '\uf201',
    'fa-calendar': '\uf073',
    'fa-clock': '\uf017',
    'fa-map-marker-alt': '\uf3c5',
    'fa-globe': '\uf0ac',
    'fa-plane': '\uf072',
    'fa-ship': '\uf1e8',
    'fa-car': '\uf1b9',
    'fa-shopping-cart': '\uf07a',
    'fa-credit-card': '\uf09d',
    'fa-building': '\uf1ad',
    'fa-hospital': '\uf0f8',
    'fa-utensils': '\uf2e7',
    'fa-coffee': '\uf0f4',
    'fa-seedling': '\uf4d8',
    'fa-tree': '\uf1bb',
    'fa-leaf': '\uf06c',
    'fa-fire': '\uf06d',
    'fa-water': '\uf0e7',
    'fa-sun': '\uf185',
    'fa-moon': '\uf186',
    'fa-snowflake': '\uf2dc',
    'fa-wind': '\uf50e',
    'fa-feather': '\uf303',
    'fa-crown': '\uf521',
    'fa-gem': '\uf3a5',
    'fa-mask': '\uf630',
    'fa-fingerprint': '\uf577',
    'fa-id-card': '\uf2c2',
    'fa-address-card': '\uf2bb',
    'fa-user-circle': '\uf2bd',
    'fa-cube': '\uf1b2',
    'fa-cubes': '\uf1b3',
    'fa-box-open': '\uf49e',
    'fa-clipboard': '\uf328',
    'fa-sticky-note': '\uf249',
    'fa-save': '\uf0c7',
    'fa-print': '\uf02f',
    'fa-download': '\uf019',
    'fa-upload': '\uf093',
    'fa-share': '\uf064',
    'fa-copy': '\uf0c5',
    'fa-trash': '\uf1f8',
    'fa-edit': '\uf044',
    'fa-plus-circle': '\uf055',
    'fa-minus-circle': '\uf056',
    'fa-check-circle': '\uf058',
    'fa-times-circle': '\uf057',
    'fa-play-circle': '\uf144',
    'fa-pause-circle': '\uf28b',
    'fa-stop-circle': '\uf28d',
    'fa-redo': '\uf01e',
    'fa-undo': '\uf0e2',
    'fa-bolt': '\uf0e7',
    'fa-magic': '\uf0d3',
    'fa-wand-sparkles': '\uf72b',
    'fa-sliders-h': '\uf1de',
    'fa-paint-brush': '\uf1fc',
    'fa-palette': '\uf53f',
    'fa-camera': '\uf030',
    'fa-microphone': '\uf130',
    'fa-headphones': '\uf025',
    'fa-music': '\uf001',
    'fa-volume-up': '\uf028',
    'fa-play': '\uf04b',
    'fa-pause': '\uf04c',
    'fa-stop': '\uf04d',
    'fa-forward': '\uf04e',
    'fa-backward': '\uf04a',
    'fa-step-forward': '\uf051',
    'fa-step-backward': '\uf048',
    'fa-random': '\uf074',
    'fa-repeat': '\uf363',
    'fa-heartbeat': '\uf21e',
    'fa-stethoscope': '\uf0f1',
    'fa-pills': '\uf484',
    'fa-syringe': '\uf48e',
    'fa-thermometer-half': '\uf2c9',
    'fa-band-aid': '\uf462',
    'fa-user-md': '\uf0f0',
    'fa-wheelchair': '\uf193',
    'fa-helicopter': '\uf533',
    'fa-ambulance': '\uf0f9',
    'fa-bus': '\uf207',
    'fa-train': '\uf238',
    'fa-subway': '\uf239',
    'fa-bicycle': '\uf206',
    'fa-walking': '\uf554',
    'fa-spa': '\uf5bb',
    'fa-spray-can': '\uf5bd',
    'fa-paint-roller': '\uf5aa',
    'fa-ruler': '\uf542',
    'fa-compass': '\uf14e',
    'fa-map': '\uf279',
    'fa-road': '\uf018',
    'fa-flag': '\uf024',
    'fa-flag-checkered': '\uf11e',
    'fa-thumbtack': '\uf08d',
    'fa-code-branch': '\uf126',
    'fa-code-commit': '\uf386',
    'fa-code-merge': '\uf387',
    'fa-project-diagram': '\uf542',
    'fa-sitemap': '\uf0e8',
    'fa-network-wired': '\uf6ff',
    'fa-hdd': '\uf0a0',
    'fa-usb': '\uf287',
    'fa-compact-disc': '\uf51f',
    'fa-memory': '\uf538',
    'fa-microchip': '\uf2db',
    'fa-broadcast-tower': '\uf519',
    'fa-satellite-dish': '\uf7c0',
    'fa-satellite': '\uf7bf',
    'fa-tv': '\uf26c',
    'fa-table': '\uf0ce',
    'fa-th': '\uf00a',
    'fa-th-large': '\uf009',
    'fa-th-list': '\uf00b',
    'fa-columns': '\uf0db',
    'fa-sort': '\uf0dc',
    'fa-sort-up': '\uf0de',
    'fa-sort-down': '\uf0dd',
    'fa-arrows-alt-h': '\uf337',
    'fa-arrows-alt-v': '\uf338',
    'fa-expand': '\uf065',
    'fa-compress': '\uf066',
    'fa-expand-arrows-alt': '\uf31e',
    'fa-compress-arrows-alt': '\uf78c',
    'fa-window-maximize': '\uf2d0',
    'fa-window-minimize': '\uf2d1',
    'fa-window-restore': '\uf2d2',
    'fa-window-close': '\uf2d3',
    'fa-object-group': '\uf247',
    'fa-object-ungroup': '\uf248',
    'fa-layer-group': '\uf5fd',
};

const FA_PATTERN = /^(?:fa|fas|far|fab|fal|fad|fass|fasr|fasl|fasd):fa-([a-zA-Z0-9-]+)(?:\s+(.+))?$/;
const ICON_PREFIX = /^(?:fa|fas|far|fab|fal|fad|fass|fasr|fasl|fasd):fa-/;
const ICON_SUFFIX = /(?:fa|fas|far|fab|fal|fad|fass|fasr|fasl|fasd):fa-[a-zA-Z0-9-]+(?:\s+)?/;

export interface ParsedIconText {
    icon?: string;
    iconCode?: string;
    text: string;
    prefix?: string;
}

export function parseIconSyntax(text: string): ParsedIconText {
    const trimmed = text.trim();
    const faMatch = trimmed.match(FA_PATTERN);
    
    if (faMatch) {
        const prefixMatch = trimmed.match(ICON_PREFIX);
        const prefix = prefixMatch ? prefixMatch[0].split(':')[0] : 'fas';
        const iconName = faMatch[1];
        const remaining = faMatch[2] || '';
        const iconCode = FONT_AWESOME_ICONS[`fa-${iconName}`];
        
        if (iconCode) {
            return {
                icon: `fa-${iconName}`,
                iconCode,
                text: remaining.trim(),
                prefix
            };
        }
    }
    
    return { text: trimmed };
}

export function getIconCode(iconName: string): string | undefined {
    return FONT_AWESOME_ICONS[iconName];
}

export function resolveIconInLabel(label: string): { displayText: string; iconCode?: string } {
    const parsed = parseIconSyntax(label);
    
    if (parsed.iconCode) {
        return {
            displayText: parsed.text,
            iconCode: parsed.iconCode
        };
    }
    
    return { displayText: label };
}
